service: template
provider:
  name: aws
  stackName: template
  runtime: python3.8
  region: sa-east-1
  memorySize: 128
  timeout: 30
functions:
  app:
    handler: src/app.handler
    # environment:
    #   DOPPLER_TOKEN: ${env:DOPPLER_TOKEN}
    events:
      - http:
        path: /
        method: get
        cors: true
      - http:
        path: /
        method: post
        cors: true
custom:
  pythonRequirements:
    dockerizePip: non-linux
package:
  exclude:
    - node_modules/**
    - package.json
    - package-lock.json
    - yarn.lock
    - start-dev.py
    - Dockerfile
    - docker-compose.yml
    - __pycache__
    - .gitignore
    - .app.log
    - .flake8
    - src/tests/**
    - test.py
    - requirements-dev.txt
    - api.py
    - mocks/**
    - setup.cfg
    - start-dev.py
    - README.md
    - asgi.py
    - .env
    - .editorconfig
    - .vscode
    - .github
plugins:
  - serverless-python-requirements
