name: Deploy

on: [push, pull_request]

jobs:
  flake8-and-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # Update with your python version
      - name: Install dependencies
        run: python3 -m pip install -r requirements.txt && python3 -m pip install flake8
      - name: Flake8
        run: python3 -m flake8
#   deploy:
#     needs: flake8-and-tests
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         node-version: [14.x]
#     steps:
#       - uses: actions/checkout@v2
#       - name: Use Node.js ${{ matrix.node-version }}
#         uses: actions/setup-node@v1
#         with:
#           node-version: ${{ matrix.node-version }}
#       - name: Set up Python
#         uses: actions/setup-python@v2
#         with:
#           python-version: 3.8  # Update with your python version
#       - name: Install serverless
#         if: ${{ github.ref == 'refs/heads/master' }}
#         run: npm i serverless -g
#       - name: Install plugins
#         if: ${{ github.ref == 'refs/heads/master' }}
#         run: npm ci
#       - name: Config
#         if: ${{ github.ref == 'refs/heads/master' }}
#         run: sls config credentials --provider aws --key ${{ secrets.AWS_ACCESS_KEY_ID }} --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }} --stage production
#       - name: Deploy
#         if: ${{ github.ref == 'refs/heads/master' }}
#         run: sls deploy --stage production
#         env:
#           DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
#           ENVIRONMENT: ${{ secrets.DOPPLER_ENVIRONMENT }}
#           BOTO3_REGION_NAME: ${{ secrets.BOTO3_REGION_NAME }}
#           BOTO3_AWS_ACCESS_KEY_ID: ${{ secrets.BOTO3_AWS_ACCESS_KEY_ID }}
#           BOTO3_AWS_SECRET_ACCESS_KEY: ${{ secrets.BOTO3_AWS_SECRET_ACCESS_KEY }}
